version: "3"
services:
    mongo-db:
        image: "mongo:${MONGO_DB_TAG}"
        hostname: "mongo-db"
        environment:
            - "MONGO_INITDB_ROOT_USERNAME=root"
            - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}"
        restart: "always"
        volumes:
            - "./mongo-db:/data/db"

    mysql:
        image: "mysql:${MYSQL_TAG}"
        hostname: "mysql"
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        restart: "always"
        volumes:
            - "./mysql:/var/lib/mysql"

    timescale:
        image: "timescale/timescaledb-postgis:${TIMESCALE_TAG}"
        hostname: "timescale"
        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            - "POSTGRES_USER=orion-ld"
            - "POSTGRES_PASSWORD=${TIMESCALE_POSTGRE_SQL_PASSWORD}"
        restart: "always"
        volumes:
            - "./timescale:/var/lib/postgresql/data"

    orion-ld:
        image: "fiware/orion-ld:${ORION_LD_TAG}"
        hostname: "orion-ld"
        ports:
            - "${ORION_LD_PORT}:1026"
        environment:
            - "ORIONLD_MONGO_HOST=mongo-db"
            - "ORIONLD_MONGO_USER=root"
            - "ORIONLD_MONGO_PASSWORD=${MONGO_DB_ROOT_PASSWORD}"
            - "ORIONLD_TROE=TRUE"
            - "ORIONLD_TROE_HOST=timescale"
            - "ORIONLD_TROE_USER=orion-ld"
            - "ORIONLD_TROE_PWD=${TIMESCALE_POSTGRE_SQL_PASSWORD}"
        restart: "always"
        depends_on:
            - "mongo-db"
            - "timescale"

    mintaka:
        image: "fiware/mintaka:${MINTAKA_TAG}"
        hostname: "mintaka"
        ports:
            - "${MINTAKA_PORT}:8080"
        environment:
            - "DATASOURCES_DEFAULT_HOST=timescale"
            - "DATASOURCES_DEFAULT_USERNAME=orion-ld"
            - "DATASOURCES_DEFAULT_PASSWORD=${TIMESCALE_POSTGRE_SQL_PASSWORD}"
            - "DATASOURCES_DEFAULT_DATABSE=orion-ld"
        restart: "always"
        depends_on:
            - "timescale"

    keyrock:
        image: "fiware/idm:${KEYROCK_TAG}"
        hostname: "keyrock"
        ports:
            - "${KEYROCK_PORT}:3000"
        environment:
            - "IDM_DB_HOST=mysql"
            - "IDM_DB_USER=root"
            - "IDM_DB_PASS=${MYSQL_ROOT_PASSWORD}"
            - "IDM_ADMIN_EMAIL=${KEYROCK_ADMIN_EMAIL}"
            - "IDM_ADMIN_PASS=${KEYROCK_ADMIN_PASSWORD}"
            - "IDM_SERVER_MAX_HEADER_SIZE=32768"
            - "IDM_AR_URL=internal"
            - "IDM_PR_ID=${I4TRUST_SATELLITE_ID}"
            - "IDM_PR_URL=${I4TRUST_SATELLITE_URL}"
            - "IDM_PR_TOKEN_ENDPOINT=${I4TRUST_SATELLITE_TOKEN_URL}"
            - "IDM_PR_PARTIES_ENDPOINT=${I4TRUST_SATELLITE_PARTIES_URL}"
            - "IDM_PR_CLIENT_ID=${CLIENT_ID}"
            - "IDM_PR_CLIENT_CRT=${CLIENT_CERTIFICATES}"
            - "IDM_PR_CLIENT_KEY=${CLIENT_PRIVATE_KEY}"
        restart: "always"
        volumes:
            - "./fiware-idm/controllers/extparticipant/utils.js:/opt/fiware-idm/controllers/extparticipant/utils.js"
            - "./fiware-idm/controllers/authregistry/authregistry.js:/opt/fiware-idm/controllers/authregistry/authregistry.js"
            - "./fiware-idm/routes/authregistry/authregistry.js:/opt/fiware-idm/routes/authregistry/authregistry.js"
        depends_on:
            - "mysql"

 #   wilma-orion-ld:
 #       image: "fiware/pep-proxy:${WILMA_ORION_LD_TAG}"
 #       hostname: "wilma-orion-ld"
 #       ports:
 #           - "${WILMA_ORION_LD_PORT}:80"
 #       environment:
 #           - "PEP_PROXY_PORT=80"
 #           - "PEP_PROXY_IDM_HOST=keyrock"
 #           - "PEP_PROXY_IDM_PORT=3000"
 #           - "PEP_PROXY_APP_HOST=orion-ld"
 #           - "PEP_PROXY_APP_PORT=1026"
 #           - "PEP_PROXY_APP_ID=${WILMA_ORION_LD_APP_ID}"
 #           - "PEP_PROXY_USERNAME=${WILMA_ORION_LD_APP_USERNAME}"
 #           - "PEP_PASSWORD=${WILMA_ORION_LD_APP_PASSWORD}"
 #       restart: "always"
 #       depends_on:
 #           - "keyrock"
 #           - "orion-ld"
 #
 #   wilma-mintaka:
 #       image: "fiware/pep-proxy:${WILMA_MINTAKA_TAG}"
 #       hostname: "wilma-mintaka"
 #       ports:
 #           - "${WILMA_MINTAKA_PORT}:80"
 #       environment:
 #           - "PEP_PROXY_PORT=80"
 #           - "PEP_PROXY_IDM_HOST=keyrock"
 #           - "PEP_PROXY_IDM_PORT=3000"
 #           - "PEP_PROXY_APP_HOST=mintaka"
 #           - "PEP_PROXY_APP_PORT=8080"
 #           - "PEP_PROXY_APP_ID=${WILMA_MINTAKA_APP_ID}"
 #           - "PEP_PROXY_USERNAME=${WILMA_MINTAKA_APP_USERNAME}"
 #           - "PEP_PASSWORD=${WILMA_MINTAKA_APP_PASSWORD}"
 #       restart: "always"
 #       depends_on:
 #           - "keyrock"
 #           - "mintaka"

    kong:
        image: "quay.io/fiware/kong:${KONG_TAG}"
        hostname: "kong"
        ports:
            - "${KONG_PORT}:8080"
        environment:
            KONG_DATABASE: "off"
            KONG_PROXY_LISTEN: "0.0.0.0:8080"
            KONG_ADMIN_LISTEN: "0.0.0.0:8000"
            KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
            KONG_ADMIN_ERROR_LOG: "/dev/stderr"
            KONG_PROXY_ACCESS_LOG: "/dev/stdout"
            KONG_PROXY_ERROR_LOG: "/dev/stderr"
            KONG_ADMIN_GUI_ACCESS_LOG: "/dev/stdout"
            KONG_ADMIN_GUI_ERROR_LOG: "/dev/stderr"
            KONG_PORTAL_API_ACCESS_LOG: "/dev/stdout"
            KONG_PORTAL_API_ERROR_LOG: "/dev/stderr"
            KONG_DECLARATIVE_CONFIG: "/opt/kong/kong.yaml"
            KONG_NGINX_WORKER_PROCESSES: "2"
            KONG_NGINX_PROXY_LARGE_CLIENT_HEADER_BUFFERS: "16 128k"
            KONG_NGINX_PROXY_HTTP2_MAX_FIELD_SIZE: "32k"
            KONG_NGINX_PROXY_HTTP2_MAX_HEADER_SIZE: "32k"
        restart: "always"
        volumes:
            - "./config/kong.yaml:/opt/kong/kong.yaml"
        depends_on:
            - "orion-ld"
            - "mintaka"

    activation-service:
        image: "i4trust/activation-service:${ACTIVATION_SERVICE_TAG}"
        hostname: "activation-service"
        ports:
            - "${ACTIVATION_SERVICE_PORT}:7000"
        volumes:
            - "./config/activation-service.yml:/home/aservice/config/as.yml"
        depends_on:
            - "keyrock"

#    nginx:
#        image: "nginx:${NGINX_TAG}"
#        hostname: "nginx"
#        ports:
#            - "443:443"
#        restart: "always"
#        volumes:
#            - "./config/nginx.conf:/etc/nginx/nginx.conf"
#            - "/etc/letsencrypt:/etc/letsencrypt"
#        depends_on:
#            - "keyrock"
#            - "wilma-orion-ld"
#            - "wilma-mintaka"
#            - "kong"
#            - "activation-service"
